# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".meteor/packages" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Restore meteor symlink when Meteor was restored from the cache
      - run: if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
      # Download Meteor if isn't already installed via the cache
      - run: if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

      - run: meteor npm install

      - save_cache:
          paths:
            - node_modules
            - .meteor
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum ".meteor/packages" }}

      - run: npm run test
