# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: meteor/circleci
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}-{{ checksum ".meteor/packages" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      # Restore meteor symlink when Meteor was restored from the cache
      - run: if [ -d ~/.meteor ]; then sudo ln -s ~/.meteor/meteor /usr/local/bin/meteor; fi
      # Download Meteor if isn't already installed via the cache
      - run: if [ ! -e $HOME/.meteor/meteor ]; then curl https://install.meteor.com | sh; fi

      - run: meteor npm install

      - save_cache:
          paths:
            - node_modules
            - .meteor/local
          key: v2-dependencies-{{ checksum "package.json" }}-{{ checksum ".meteor/packages" }}

      - run: npm run test
